# fly.toml app configuration file for blackout-app (frontend)
app = "blackout-app"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"
  target     = "prod"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0