# fly.toml app configuration file generated for blackout-db on 2025-05-09T18:55:39+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blackout-db"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"
  target = "prod"  # 👈 ADD THIS to use the production stage

[http_service]
  internal_port = 5050  # 👈 must match `EXPOSE` and your server's listen port
  handlers = ["http","tls","websocket"]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1